package terraform

import (
	"fmt"
	"sort"
	"strings"

	"github.com/francescocitti/go-escalation-check/internal/escalation"
)

func Export(findings []escalation.Finding) string {
	var sb strings.Builder

	sb.WriteString(`# Generated by go-escalation-check
# Deny-based JIT restriction policies for each principal with a detected
# privilege escalation path. Review carefully before applying to production.
# https://github.com/francescocitti/go-escalation-check

`)

	byPrincipal := make(map[string][]escalation.Finding)
	for _, f := range findings {
		byPrincipal[f.PrincipalARN] = append(byPrincipal[f.PrincipalARN], f)
	}

	arns := make([]string, 0, len(byPrincipal))
	for arn := range byPrincipal {
		arns = append(arns, arn)
	}
	sort.Strings(arns)

	for _, arn := range arns {
		pf := byPrincipal[arn]
		sb.WriteString(renderPrincipal(arn, pf))
	}

	return sb.String()
}

func renderPrincipal(arn string, findings []escalation.Finding) string {
	dangerous := make(map[string]bool)
	for _, f := range findings {
		for _, a := range f.Technique.Required {
			dangerous[a] = true
		}
	}

	actions := make([]string, 0, len(dangerous))
	for a := range dangerous {
		actions = append(actions, a)
	}
	sort.Strings(actions)

	lines := make([]string, len(actions))
	for i, a := range actions {
		lines[i] = fmt.Sprintf("        %q,", a)
	}

	tfName := terraformName(arn)
	principalName := arnShortName(arn)
	kind := "user"
	if strings.Contains(arn, ":role/") {
		kind = "role"
	}

	var sb strings.Builder

	sb.WriteString(fmt.Sprintf(`resource "aws_iam_policy" "jit_restrict_%s" {
  name        = "jit_restrict_%s"
  description = "Deny escalation paths for %s (go-escalation-check)"

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid      = "DenyEscalationPaths"
        Effect   = "Deny"
        Action   = [
%s
        ]
        Resource = "*"
        Condition = {
          Bool = {
            "aws:MultiFactorAuthPresent" = "false"
          }
        }
      }
    ]
  })
}

`, tfName, tfName, arn, strings.Join(lines, "\n")))

	if kind == "user" {
		sb.WriteString(fmt.Sprintf(`resource "aws_iam_user_policy_attachment" "jit_restrict_%s" {
  user       = %q
  policy_arn = aws_iam_policy.jit_restrict_%s.arn
}

`, tfName, principalName, tfName))
	} else {
		sb.WriteString(fmt.Sprintf(`resource "aws_iam_role_policy_attachment" "jit_restrict_%s" {
  role       = %q
  policy_arn = aws_iam_policy.jit_restrict_%s.arn
}

`, tfName, principalName, tfName))
	}

	return sb.String()
}

func terraformName(arn string) string {
	name := arnShortName(arn)
	name = strings.ToLower(name)
	name = strings.NewReplacer(".", "_", "@", "_at_").Replace(name)
	return name
}

func arnShortName(arn string) string {
	parts := strings.Split(arn, "/")
	return parts[len(parts)-1]
}
